name: MiningTrophies-stats
version: ${project.version}
description: Simulates miningtrophies drops for testing
authors: [crashdemons]

api-version: 1.13

main: com.github.crashdemons.phsim.MTSimPlugin
database: false

depend: [PlayerHeads]